# Generated by Django 4.0.2 on 2022-06-09 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Категория')),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='LeverKeyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('keyBitWidth', models.FloatField(verbose_name='Ширина бородки')),
                ('keyStemDiametr', models.FloatField(verbose_name='Диаметр стержня')),
                ('keyStemLenght', models.IntegerField(verbose_name='Длинна стержня')),
                ('keyImage', models.ImageField(upload_to='imagekey/', verbose_name='Изображение')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leverKeyModel', to='oauth_app.category')),
            ],
        ),
    ]
