# Generated by Django 4.0.2 on 2022-06-16 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PinKeyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('keyWidth', models.FloatField(verbose_name='Ширина заготовки')),
                ('keyThickness', models.FloatField(verbose_name='Толщина заготовки')),
                ('keyLenght', models.FloatField(verbose_name='Длинна заготовки')),
                ('keyProfile', models.ImageField(upload_to='imageprofile/', verbose_name='Изображение')),
                ('keyObject', models.FileField(blank=True, upload_to='uploads')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinKeyModel', to='oauth_app.category')),
            ],
        ),
        migrations.AddField(
            model_name='leverkeymodel',
            name='keyObject',
            field=models.FileField(blank=True, upload_to='uploads'),
        ),
        migrations.CreateModel(
            name='StandartSizePinKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSize', models.IntegerField(verbose_name='Типоразмер')),
                ('standartSize', models.FloatField(verbose_name='Размер')),
                ('pinKeyModel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pinKeyModel', to='oauth_app.pinkeymodel')),
            ],
        ),
        migrations.CreateModel(
            name='StandartSizeLeverKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameSize', models.IntegerField(verbose_name='Типоразмер')),
                ('standartSize', models.FloatField(verbose_name='Размер')),
                ('leverKeyModel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leverKeyModel', to='oauth_app.leverkeymodel')),
            ],
        ),
    ]
