# Generated by Django 4.0.2 on 2022-06-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0002_pinkeymodel_leverkeymodel_keyobject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailUser', models.EmailField(max_length=100)),
                ('objectKey', models.JSONField()),
            ],
        ),
    ]
